// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nn_heuristic_cpp
IntegerVector nn_heuristic_cpp(NumericMatrix dist_mat, int start);
RcppExport SEXP _tspR_nn_heuristic_cpp(SEXP dist_matSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_heuristic_cpp(dist_mat, start));
    return rcpp_result_gen;
END_RCPP
}
// two_opt_cpp
IntegerVector two_opt_cpp(IntegerVector tour, NumericMatrix dist_mat);
RcppExport SEXP _tspR_two_opt_cpp(SEXP tourSEXP, SEXP dist_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type tour(tourSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    rcpp_result_gen = Rcpp::wrap(two_opt_cpp(tour, dist_mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tspR_nn_heuristic_cpp", (DL_FUNC) &_tspR_nn_heuristic_cpp, 2},
    {"_tspR_two_opt_cpp", (DL_FUNC) &_tspR_two_opt_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tspR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
