# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nn_heuristic_cpp <- function(dist_mat, start) {
    .Call(`_tspR_nn_heuristic_cpp`, dist_mat, start)
}

two_opt_cpp <- function(tour, dist_mat) {
    .Call(`_tspR_two_opt_cpp`, tour, dist_mat)
}

